### ISSUE TITLE
Search Help does not work on customer system

### ISSUE THREAD

**Issue by WegnerDan** [abap2UI5/abap2UI5#343]
First off, I have no idea if I'm doing something wrong or there is a bug somewhere or the system I'm working on is broken somehow.

I'm building a small app in a customer system and I'm trying to put in a couple search helps. 

I've made a test class for this issue. The problem does not occur in my personal SAP system with config value "src" set to `https://sdk.openui5.org/resources/sap-ui-core.js`.

I do not have internet access in the development VM used for the customer system, so I used `/sap/public/bc/ui5_ui5/resources/sap-ui-core.js` as src config value. 

Every time I click the search help button, this appears in the js console:
![image](https://github.com/abap2UI5/abap2UI5/assets/6908247/9d65378f-a005-47d5-8453-e46bafcf6890)

<details>
<summary>complete console output</summary>

```
Device-dbg.js:85 2023-07-05 23:28:06 Device API logging initialized - DEVICE
Log-dbg.js:452  2023-07-05 23:28:07.356800 During a clone operation, a template was found that neither was marked with 'templateShareable:true' nor 'templateShareable:false'. The framework won't destroy the template. This could cause errors (e.g. duplicate IDs) or memory leaks (The template is used in aggregation 'suggestionItems' of object '__input0').For more information, see documentation under 'Aggregation Binding'. -  
f @ Log-dbg.js:452
Promise.then (async)
responseSuccess @ zcl_2ui5_table_test_2:231
xhr.onload @ zcl_2ui5_table_test_2:260
load (async)
readHttp @ zcl_2ui5_table_test_2:255
Roundtrip @ zcl_2ui5_table_test_2:280
(anonymous) @ zcl_2ui5_table_test_2:306
(anonymous) @ Core-dbg.js:1396
X._executeInitListeners @ Core-dbg.js:1395
X._executeInitialization @ Core-dbg.js:1408
X.init @ Core-dbg.js:1233
(anonymous) @ Core-dbg.js:475
m @ Core-dbg.js:168
W.finishTask @ Core-dbg.js:162
s1 @ Core-dbg.js:482
Log-dbg.js:452  2023-07-05 23:28:14.476800 During a clone operation, a template was found that neither was marked with 'templateShareable:true' nor 'templateShareable:false'. The framework won't destroy the template. This could cause errors (e.g. duplicate IDs) or memory leaks (The template is used in aggregation 'suggestionItems' of object '__input1').For more information, see documentation under 'Aggregation Binding'. -  
f @ Log-dbg.js:452
L.error @ Log-dbg.js:232
W @ ManagedObject-dbg.js:5177
o.clone @ ManagedObject-dbg.js:5213
d.clone @ Element-dbg.js:1331
c.clone @ Control-dbg.js:281
C.clone @ CustomStyleClassSupport-dbg.js:73
A.clone @ Input-dbg.js:2384
o.clone @ ManagedObject-dbg.js:5118
d.clone @ Element-dbg.js:1331
c.clone @ Control-dbg.js:281
C.clone @ CustomStyleClassSupport-dbg.js:73
b.factory @ ManagedObject-dbg.js:3904
H @ ManagedObject-dbg.js:4135
o.updateAggregation @ ManagedObject-dbg.js:4222
t.updateItems @ ListBase-dbg.js:646
A.update @ ManagedObjectMetadata-dbg.js:390
l @ ManagedObject-dbg.js:3944
b.fireEvent @ EventProvider-dbg.js:247
B._fireChange @ Binding-dbg.js:434
J.checkUpdate @ JSONListBinding-dbg.js:163
B.initialize @ Binding-dbg.js:586
o._bindAggregation @ ManagedObject-dbg.js:3995
t._bindAggregation @ ListBase-dbg.js:713
o.updateBindings @ ManagedObject-dbg.js:4414
o._propagateProperties @ ManagedObject-dbg.js:4888
o.propagateProperties @ ManagedObject-dbg.js:4869
o._propagateProperties @ ManagedObject-dbg.js:4891
o.propagateProperties @ ManagedObject-dbg.js:4863
o._propagateProperties @ ManagedObject-dbg.js:4891
o.propagateProperties @ ManagedObject-dbg.js:4869
o.setModel @ ManagedObject-dbg.js:4757
(anonymous) @ zcl_2ui5_table_test_2:232
Promise.then (async)
responseSuccess @ zcl_2ui5_table_test_2:231
xhr.onload @ zcl_2ui5_table_test_2:260
load (async)
readHttp @ zcl_2ui5_table_test_2:255
Roundtrip @ zcl_2ui5_table_test_2:280
onEvent @ zcl_2ui5_table_test_2:203
F @ ExpressionParser-dbg.js:391
(anonymous) @ ExpressionParser-dbg.js:704
x @ ExpressionParser-dbg.js:884
f.getExternalValue @ CompositeBinding-dbg.js:268
g @ EventHandlerResolver-dbg.js:357
eval @ EventHandlerResolver-dbg.js:171
b.fireEvent @ EventProvider-dbg.js:247
d.fireEvent @ Element-dbg.js:631
(anonymous) @ ManagedObjectMetadata-dbg.js:789
A._fireValueHelpRequest @ Input-dbg.js:1170
press @ Input-dbg.js:1103
b.fireEvent @ EventProvider-dbg.js:247
d.fireEvent @ Element-dbg.js:631
(anonymous) @ ManagedObjectMetadata-dbg.js:789
e.<computed> @ Icon-dbg.js:295
d._handleEvent @ Element-dbg.js:342
U._handleEvent @ UIArea-dbg.js:947
dispatch @ jquery-dbg.js:5430
t3.handle @ jquery-dbg.js:5234
ui5loader-dbg.js:1279 
        
        
        GET http://rftsapds4a1.rft.msgcloud.de:50000/sap/public/bc/ui5_ui5/1/resources/sap/m/footer.js 404 (NOT FOUND)
u1 @ ui5loader-dbg.js:1279
x1 @ ui5loader-dbg.js:1534
z1 @ ui5loader-dbg.js:1726
l @ ui5loader-dbg.js:1983
eval @ XMLTemplateProcessor-dbg.js:870
h1 @ XMLTemplateProcessor-dbg.js:869
j1 @ XMLTemplateProcessor-dbg.js:994
i1 @ XMLTemplateProcessor-dbg.js:937
E1 @ XMLTemplateProcessor-dbg.js:1347
Promise.then (async)
p @ XMLTemplateProcessor-dbg.js:208
k1 @ XMLTemplateProcessor-dbg.js:1413
j1 @ XMLTemplateProcessor-dbg.js:1001
eval @ XMLTemplateProcessor-dbg.js:767
(anonymous) @ SyncPromise-dbg.js:309
c @ SyncPromise-dbg.js:60
S @ SyncPromise-dbg.js:225
S.then @ SyncPromise-dbg.js:308
f1 @ XMLTemplateProcessor-dbg.js:764
g1 @ XMLTemplateProcessor-dbg.js:828
f1 @ XMLTemplateProcessor-dbg.js:758
G @ XMLTemplateProcessor-dbg.js:613
z.parseTemplatePromise @ XMLTemplateProcessor-dbg.js:340
init @ Fragment-dbg.js:812
F._initCompositeSupport @ Fragment-dbg.js:190
(anonymous) @ ManagedObject-dbg.js:529
constructor @ ManagedObject-dbg.js:553
constructor @ Fragment-dbg.js:122
d @ Fragment-dbg.js:395
f @ Fragment-dbg.js:414
F.load @ Fragment-dbg.js:511
onAfterRendering @ zcl_2ui5_table_test_2:63
b.fireEvent @ EventProvider-dbg.js:247
d.fireEvent @ Element-dbg.js:631
(anonymous) @ ManagedObjectMetadata-dbg.js:789
g.onAfterRendering @ View-dbg.js:751
d._handleEvent @ Element-dbg.js:342
h1 @ RenderManager-dbg.js:1285
i1 @ RenderManager-dbg.js:1370
R.render @ RenderManager-dbg.js:1520
U.rerender @ UIArea-dbg.js:643
X.renderPendingUIUpdates @ Core-dbg.js:2888
setTimeout (async)
X.addInvalidatedUIArea @ Core-dbg.js:2827
U.addInvalidatedControl @ UIArea-dbg.js:543
U.invalidate @ UIArea-dbg.js:522
o.setParent @ ManagedObject-dbg.js:2647
o.addAggregation @ ManagedObject-dbg.js:2172
U.addContent @ UIArea-dbg.js:379
(anonymous) @ Object-dbg.js:255
c.placeAt @ Control-dbg.js:670
(anonymous) @ zcl_2ui5_table_test_2:237
Promise.then (async)
responseSuccess @ zcl_2ui5_table_test_2:231
xhr.onload @ zcl_2ui5_table_test_2:260
load (async)
readHttp @ zcl_2ui5_table_test_2:255
Roundtrip @ zcl_2ui5_table_test_2:280
onEvent @ zcl_2ui5_table_test_2:203
F @ ExpressionParser-dbg.js:391
(anonymous) @ ExpressionParser-dbg.js:704
x @ ExpressionParser-dbg.js:884
f.getExternalValue @ CompositeBinding-dbg.js:268
g @ EventHandlerResolver-dbg.js:357
eval @ EventHandlerResolver-dbg.js:171
b.fireEvent @ EventProvider-dbg.js:247
d.fireEvent @ Element-dbg.js:631
(anonymous) @ ManagedObjectMetadata-dbg.js:789
A._fireValueHelpRequest @ Input-dbg.js:1170
press @ Input-dbg.js:1103
b.fireEvent @ EventProvider-dbg.js:247
d.fireEvent @ Element-dbg.js:631
(anonymous) @ ManagedObjectMetadata-dbg.js:789
e.<computed> @ Icon-dbg.js:295
d._handleEvent @ Element-dbg.js:342
U._handleEvent @ UIArea-dbg.js:947
dispatch @ jquery-dbg.js:5430
t3.handle @ jquery-dbg.js:5234
ui5loader-dbg.js:1042  Uncaught (in promise) ModuleError: failed to load 'sap/m/footer.js' from /sap/public/bc/ui5_ui5/1/resources/sap/m/footer.js: 404 - NOT FOUND
    at p1 (http://rftsapds4a1.rft.msgcloud.de:50000/sap/public/bc/ui5_ui5/1/resources/sap-ui-core.js:53:213)
    at j1.failWith (http://rftsapds4a1.rft.msgcloud.de:50000/sap/public/bc/ui5_ui5/1/resources/sap-ui-core.js:40:43)
    at x1 (http://rftsapds4a1.rft.msgcloud.de:50000/sap/public/bc/ui5_ui5/1/resources/sap-ui-core.js:62:2390)
    at z1 (http://rftsapds4a1.rft.msgcloud.de:50000/sap/public/bc/ui5_ui5/1/resources/sap-ui-core.js:64:474)
    at Object.l [as require] (http://rftsapds4a1.rft.msgcloud.de:50000/sap/public/bc/ui5_ui5/1/resources/sap-ui-core.js:69:544)
    at eval (http://rftsapds4a1.rft.msgcloud.de:50000/sap/public/bc/ui5_ui5/1/resources/sap/ui/core/library-preload.js?eval:1258:4104)
    at new Promise (<anonymous>)
    at h1 (http://rftsapds4a1.rft.msgcloud.de:50000/sap/public/bc/ui5_ui5/1/resources/sap/ui/core/library-preload.js?eval:1258:4069)
    at j1 (http://rftsapds4a1.rft.msgcloud.de:50000/sap/public/bc/ui5_ui5/1/resources/sap/ui/core/library-preload.js?eval:1258:5501)
    at i1 (http://rftsapds4a1.rft.msgcloud.de:50000/sap/public/bc/ui5_ui5/1/resources/sap/ui/core/library-preload.js?eval:1258:4906)
Caused by: XHRLoadError: 404 - NOT FOUND
    at j (http://rftsapds4a1.rft.msgcloud.de:50000/sap/public/bc/ui5_ui5/1/resources/sap-ui-core.js:58:59)
    at XMLHttpRequest.<anonymous> (http://rftsapds4a1.rft.msgcloud.de:50000/sap/public/bc/ui5_ui5/1/resources/sap-ui-core.js:58:314)
    at u1 (http://rftsapds4a1.rft.msgcloud.de:50000/sap/public/bc/ui5_ui5/1/resources/sap-ui-core.js:58:408)
    at x1 (http://rftsapds4a1.rft.msgcloud.de:50000/sap/public/bc/ui5_ui5/1/resources/sap-ui-core.js:62:2361)
    at z1 (http://rftsapds4a1.rft.msgcloud.de:50000/sap/public/bc/ui5_ui5/1/resources/sap-ui-core.js:64:474)
    at Object.l [as require] (http://rftsapds4a1.rft.msgcloud.de:50000/sap/public/bc/ui5_ui5/1/resources/sap-ui-core.js:69:544)
    at eval (http://rftsapds4a1.rft.msgcloud.de:50000/sap/public/bc/ui5_ui5/1/resources/sap/ui/core/library-preload.js?eval:1258:4104)
    at new Promise (<anonymous>)
    at h1 (http://rftsapds4a1.rft.msgcloud.de:50000/sap/public/bc/ui5_ui5/1/resources/sap/ui/core/library-preload.js?eval:1258:4069)
    at j1 (http://rftsapds4a1.rft.msgcloud.de:50000/sap/public/bc/ui5_ui5/1/resources/sap/ui/core/library-preload.js?eval:1258:5501)
p1 @ ui5loader-dbg.js:1042
j1.failWith @ ui5loader-dbg.js:814
x1 @ ui5loader-dbg.js:1539
z1 @ ui5loader-dbg.js:1726
l @ ui5loader-dbg.js:1983
eval @ XMLTemplateProcessor-dbg.js:870
h1 @ XMLTemplateProcessor-dbg.js:869
j1 @ XMLTemplateProcessor-dbg.js:994
i1 @ XMLTemplateProcessor-dbg.js:937
E1 @ XMLTemplateProcessor-dbg.js:1347
Promise.then (async)
onAfterRendering @ zcl_2ui5_table_test_2:66
b.fireEvent @ EventProvider-dbg.js:247
d.fireEvent @ Element-dbg.js:631
(anonymous) @ ManagedObjectMetadata-dbg.js:789
g.onAfterRendering @ View-dbg.js:751
d._handleEvent @ Element-dbg.js:342
h1 @ RenderManager-dbg.js:1285
i1 @ RenderManager-dbg.js:1370
R.render @ RenderManager-dbg.js:1520
U.rerender @ UIArea-dbg.js:643
X.renderPendingUIUpdates @ Core-dbg.js:2888
setTimeout (async)
X.addInvalidatedUIArea @ Core-dbg.js:2827
U.addInvalidatedControl @ UIArea-dbg.js:543
U.invalidate @ UIArea-dbg.js:522
o.setParent @ ManagedObject-dbg.js:2647
o.addAggregation @ ManagedObject-dbg.js:2172
U.addContent @ UIArea-dbg.js:379
(anonymous) @ Object-dbg.js:255
c.placeAt @ Control-dbg.js:670
(anonymous) @ zcl_2ui5_table_test_2:237
Promise.then (async)
responseSuccess @ zcl_2ui5_table_test_2:231
xhr.onload @ zcl_2ui5_table_test_2:260
load (async)
readHttp @ zcl_2ui5_table_test_2:255
Roundtrip @ zcl_2ui5_table_test_2:280
onEvent @ zcl_2ui5_table_test_2:203
F @ ExpressionParser-dbg.js:391
(anonymous) @ ExpressionParser-dbg.js:704
x @ ExpressionParser-dbg.js:884
f.getExternalValue @ CompositeBinding-dbg.js:268
g @ EventHandlerResolver-dbg.js:357
eval @ EventHandlerResolver-dbg.js:171
b.fireEvent @ EventProvider-dbg.js:247
d.fireEvent @ Element-dbg.js:631
(anonymous) @ ManagedObjectMetadata-dbg.js:789
A._fireValueHelpRequest @ Input-dbg.js:1170
press @ Input-dbg.js:1103
b.fireEvent @ EventProvider-dbg.js:247
d.fireEvent @ Element-dbg.js:631
(anonymous) @ ManagedObjectMetadata-dbg.js:789
e.<computed> @ Icon-dbg.js:295
d._handleEvent @ Element-dbg.js:342
U._handleEvent @ UIArea-dbg.js:947
dispatch @ jquery-dbg.js:5430
t3.handle @ jquery-dbg.js:5234

```

</details>

<details>
<summary>ABAP Code</summary>

```abap
CLASS zcl_2ui5_table_test_2 DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    INTERFACES:
      z2ui5_if_app.
    TYPES:
      BEGIN OF ty_line,
        selkz TYPE abap_bool,
        plant TYPE werks_d,
      END OF ty_line,
      ty_output_tab TYPE STANDARD TABLE OF ty_line,
      BEGIN OF ty_plant_suggestionitem,
        is_selected TYPE abap_bool,
        plant       TYPE werks_d,
        name        TYPE t001w-name1,
      END OF ty_plant_suggestionitem,
      ty_plant_suggestionitems TYPE STANDARD TABLE OF ty_plant_suggestionitem.
    DATA:
      is_initialized        TYPE abap_bool,
      output_table          TYPE ty_output_tab,
      plant_suggestionitems TYPE ty_plant_suggestionitems.
  PROTECTED SECTION.
  PRIVATE SECTION.
    DATA:
      client TYPE REF TO z2ui5_if_client.
    METHODS set_view.
    METHODS f4help.
ENDCLASS.



CLASS zcl_2ui5_table_test_2 IMPLEMENTATION.

  METHOD z2ui5_if_app~main.
    me->client = client.

    IF is_initialized = abap_false.
      is_initialized = abap_true.
      output_table = VALUE #(
                          ( plant = '0001' )
                          ( plant = '    ' )
                     ).
      SELECT FROM t001w
      FIELDS werks AS plant, name1 AS name
      ORDER BY werks
      INTO CORRESPONDING FIELDS OF TABLE @plant_suggestionitems.
    ENDIF.


    CASE client->get( )-event.
      WHEN 'F4TEST'.
        f4help( ).
    ENDCASE.


    set_view( ).

  ENDMETHOD.


  METHOD set_view.
    DATA(view) = z2ui5_cl_xml_view=>factory( client ).
    DATA(page) = view->shell(
        )->page(
                title          = `Value Help Testing Stuff`
                navbuttonpress = client->_event( 'BACK' )
                  shownavbutton = abap_true
            )->header_content(
                )->link(
                    text = 'Demo' target = '_blank'
                    href = 'https://twitter.com/abap2UI5/status/1630240894581608448'
                )->link(
                    text = 'Source_Code' target = '_blank'
                    href = view->hlp_get_source_code_url(  )
        )->get_parent( ).



    DATA(tab) = page->table(
            items = client->_bind_edit( output_table )
            mode  = 'MultiSelect'
        )->header_toolbar(
            )->overflow_toolbar(
                )->title( 'todo: put title here'
                )->toolbar_spacer(
                )->button(
                    text  = `test!`
                    press = client->_event( 'SEND' )
        )->get_parent( )->get_parent( ).

    tab->columns( )->column(  )->text( 'Plant' ).

    tab->items( )->column_list_item( selected = `{SELKZ}`
      )->cells(
        )->input( value = `{PLANT}`
                  showsuggestion = abap_true
                  suggestionitems = client->_bind( plant_suggestionitems )
                  showvaluehelp = abap_true
                  valuehelprequest   = client->_event( val   = 'F4TEST'
                                                       t_arg = VALUE #( ( `${PLANT}` ) ) )
       )->get( )->suggestion_items( )->get( )->list_item( text           = `{PLANT}`
                                                          additionaltext = `{NAME}`
    ).


    client->view_display( view->stringify( ) ).
  ENDMETHOD.


  METHOD f4help.
    DATA(popup) = z2ui5_cl_xml_view=>factory_popup( client ).

    popup->dialog( 'abap2UI5 - F4 Value Help'
    )->table(
            mode  = 'SingleSelectLeft'
            items = client->_bind( plant_suggestionitems )
        )->columns(
            )->column( '20rem'
                )->text( 'Plant' )->get_parent(
            )->column(
                )->text( 'Name'
        )->get_parent( )->get_parent(
        )->items(
            )->column_list_item( selected = '{IS_SELECTED}'
                )->cells(
                    )->text( '{PLANT}'
                    )->text( '{NAME}'
)->get_parent( )->get_parent( )->get_parent( )->get_parent(
    )->footer(
        )->overflow_toolbar(
            )->toolbar_spacer(
            )->button(
                text  = 'continue'
                press = client->_event( 'POPUP_TABLE_F4_CONTINUE' )
                type  = 'Emphasized'
                ).
    client->popup_display( popup->stringify( ) ).
*        DATA(stuff) = client->get( ).
*        BREAK-POINT.
  ENDMETHOD.

ENDCLASS.
```

</details>

If I comment out the call of abap method footer() in method f4help, I get the search help popup without the footer:
![image](https://github.com/abap2UI5/abap2UI5/assets/6908247/ee6d4e98-9c98-4817-9470-4c4f673eda5a)

**Comment by choper725** [comment]
write in console sap.ui.version, what is it?

**Comment by WegnerDan** [comment]
> write in console sap.ui.version, what is it?
1.96.12

<details>
<summary>Details</summary>


The following libraries are available:
Library	Version:1.96
(1.96.14)
com.sap.apf.apf-lib	1.96.0
com.sap.ca.scfld.md	1.96.0
com.sap.ca.ui	1.96.0
com.sap.collaboration.collaboration-commons	1.96.0
com.sap.esh.sap.esh.search.ui	1.96.1
com.sap.feedback.sap.feedback.ui	1.96.1
com.sap.gantt.gantt.lib	1.96.9
com.sap.ip.bi.zen.rt.components.crosstab.phx	1.96.2
com.sap.ip.bi.zen.rt.dsh.phx	1.96.2
com.sap.ip.bi.zen.rt.zencopy.phx	1.96.2
com.sap.lm.uiext.landvisz.sap.landvisz	1.96.0
com.sap.ovp.ovp-lib	1.96.7
com.sap.rules.sap.rules.ui	1.96.0
com.sap.sac.com.sap.sac.grid	1.96.2
com.sap.suite.suite-ui-commons	1.96.5
com.sap.suite.suite-ui-microchart	1.96.12
com.sap.suite.ui.generic.template.sap.suite.ui.generic.template	1.96.11
com.sap.ui5.chart	1.96.12
com.sap.ui5.codeeditor	1.96.12
com.sap.ui5.commons	1.96.12
com.sap.ui5.comp	1.96.12
com.sap.ui5.core	1.96.12
com.sap.ui5.dist.fiori-lib	1.96.14
com.sap.ui5.dist.sap.ui.server.abap	1.96.14
com.sap.ui5.dt	1.96.12
com.sap.ui5.export	1.96.12
com.sap.ui5.fiori	1.96.12
com.sap.ui5.fl	1.96.12
com.sap.ui5.generic-app	1.96.0
com.sap.ui5.generic-template	1.96.0
com.sap.ui5.inbox	1.96.12
com.sap.ui5.integration	1.96.12
com.sap.ui5.layout	1.96.12
com.sap.ui5.makit	1.96.12
com.sap.ui5.mdc	1.96.12
com.sap.ui5.mobile	1.96.12
com.sap.ui5.mobile-ext	1.96.12
com.sap.ui5.ndc	1.96.12
com.sap.ui5.resource	1.96.12
com.sap.ui5.richtexteditor	1.96.12
com.sap.ui5.rta	1.96.12
com.sap.ui5.suite	1.96.12
com.sap.ui5.support	1.96.12
com.sap.ui5.table	1.96.12
com.sap.ui5.testrecorder	1.96.12
com.sap.ui5.themelib_sap_belize	1.96.12
com.sap.ui5.themelib_sap_bluecrystal	1.96.12
com.sap.ui5.themelib_sap_fiori_3	1.96.12
com.sap.ui5.themelib_sap_horizon	1.96.12
com.sap.ui5.tnt	1.96.12
com.sap.ui5.unified	1.96.12
com.sap.ui5.ux3	1.96.12
com.sap.ui5.vbm	1.96.6
com.sap.ui5.viz	1.96.12
com.sap.ui5.vizkit.sap.ui.vk	1.96.3
com.sap.ui5.vtm.sap.ui.vtm	1.96.0
com.sap.ushell.ushell-lib	1.96.13
com.sap.ushell.ushell_abap	1.96.13
com.sap.uxap.uxap-uilib	1.96.12
com.sap.uxeng.sap.fe.common	1.96.12
com.sap.uxeng.sap.fe.core	1.96.12
com.sap.uxeng.sap.fe.macros	1.96.12
com.sap.uxeng.sap.fe.navigation	1.96.12
com.sap.uxeng.sap.fe.placeholder	1.96.12
com.sap.uxeng.sap.fe.plugins	1.96.12
com.sap.uxeng.sap.fe.semantics	1.96.12
com.sap.uxeng.sap.fe.templates	1.96.12
com.sap.uxeng.sap.fe.test	1.96.12
com.sap.uxeng.sap.fe.tools	1.96.12
com.sap.webanalytics.sap.webanalytics.core	1.96.0

</details>

**Comment by choper725** [comment]
i think footer in dialog is not in that version..

**Comment by WegnerDan** [comment]
https://sapui5.hana.ondemand.com/sdk#/api/sap.m.Dialog%23overview 

I can't find footer here anywhere. 
Where would one find that information? 

What can I use alternatively?

**Comment by choper725** [comment]
in aggregations.

try maybe vbox with buttons ??

**Comment by WegnerDan** [comment]
https://sapui5.hana.ondemand.com/1.96.12/#/api/sap.m.Dialog%23aggregations 

This has a buttons aggregation, but I don't understand how to use it. 


The footer aggregation is not available in this version, you're correct.

**Comment by WegnerDan** [comment]
This is what I've tried so far:
```abap
  METHOD popup_f4help.
    DATA(event_arguments) = client->get( )-t_event_arg.
    DATA(fieldname) = event_arguments[ 1 ].
    DATA(current_field_content) = event_arguments[ 2 ].



    DATA(popup) = z2ui5_cl_xml_view=>factory_popup( client ).

    popup->dialog( 'abap2UI5 - F4 Value Help'
    )->table(
            mode  = 'SingleSelectLeft'
            items = client->_bind( zpkn_material->key-char_suggestion_items[ name = fieldname ]-suggestion_items )
        )->columns(
            )->column( '20rem'
                )->text( 'Color' )->get_parent(
            )->column(
                )->text( 'Description'
        )->get_parent( )->get_parent(
        )->items(
            )->column_list_item( selected = '{IS_SELECTED}'
                )->cells(
                    )->text( '{VALUE}'
                    )->text( '{DESCR}'
*    )->get_parent( )->get_parent( )->get_parent( )->get_parent(
    )->get_parent( )->get_parent( )->get_parent( )->get_parent( )->get_parent(
    )->buttons( )->button(  text    = 'TEST' ).
*footer(
*        )->overflow_toolbar(
*            )->toolbar_spacer(
*            )->button(
*                text  = 'continue'
*                press = client->_event( 'POPUP_TABLE_F4_CONTINUE' )
*                type  = 'Emphasized'
*                ).
    client->popup_display( popup->stringify( ) ).
  ENDMETHOD.
```

**Comment by WegnerDan** [comment]
Since I'm using the search help in an editable table, I need to know in which row the search help button was pressed.

I have found t_arg in client->_event and I'm using it to find the current value of the table input field and the name of the component. 
Is there a way to get the table index of the table that is bound with client->_bind_edit?

**Comment by choper725** [comment]
is_selected got the value you want no?

**Comment by WegnerDan** [comment]
is_selected of the table used in the value help has it, but I also need to know which row of the editable table has triggered the search help popup call.

**Comment by oblomov-dev** [comment]
maybe make an additional column with indexes (filled by yourself) and then send this col also back with the t_arguments. I think in one of the list demos i did it this way.

**Comment by WegnerDan** [comment]
> maybe make an additional column with indexes

That's a good idea, that works!

Slightly related: How exactly does t_arg work? 
I found `${propertyName}` gets me the content of a field and `'somevalue'` lets me transfer values from abap back to abap, is there anything else that can be done with t_arg?

**Comment by oblomov-dev** [comment]
The idea of t_arg is to have a generic way to send data from frontend to backend. And you can decide which values are interesting for you and send this values back to abap.

Check this document:
https://openui5.hana.ondemand.com/#/topic/b0fb4de7364f4bcbb053a99aa645affe

UI5 gives you the following objects in an XML View:
$event , $source, $parameters

**Comment by WegnerDan** [comment]
Thank you, that's exactly what I was looking for yesterday.
