### ISSUE TITLE
Error when try to load FilterBar

### ISSUE THREAD

**Issue by abagrevatil** [abap2UI5/abap2UI5#638]
Hello,

When I am trying to create a filter bar on the browser console appears the following errors:

> Access to XMLHttpRequest at 'https://sdk.openui5.org/resources/~202310301319~/sap/ui/comp/filterbar/FilterBar.js' from origin 'http://vasssapdes:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
je @ ui5loader-dbg.js:1391
ui5loader-dbg.js:1391     Failed to load resource: net::ERR_FAILED
je @ ui5loader-dbg.js:1391
zabap2ui5:1 Uncaught (in promise) ModuleError: failed to load 'sap/ui/comp/filterbar/FilterBar.js' from https://sdk.openui5.org/resources/~202310301319~/sap/ui/comp/filterbar/FilterBar.js: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://sdk.openui5.org/resources/~202310301319~/sap/ui/comp/filterbar/FilterBar.js'.
    at we (https://sdk.openui5.org/resources/~202310301319~/sap-ui-core.js:10:6645)
    at ge.failWith (https://sdk.openui5.org/resources/~202310301319~/sap-ui-core.js:10:4709)
    at qe (https://sdk.openui5.org/resources/~202310301319~/sap-ui-core.js:10:13203)
    at Oe (https://sdk.openui5.org/resources/~202310301319~/sap-ui-core.js:10:15205)
    at Object.r [as require] (https://sdk.openui5.org/resources/~202310301319~/sap-ui-core.js:10:18588)
    at eval (https://sdk.openui5.org/resources/~202310301319~/sap/ui/core/library-preload.js?eval:784:8093)
    at new Promise (<anonymous>)
    at ne (https://sdk.openui5.org/resources/~202310301319~/sap/ui/core/library-preload.js?eval:784:8060)
    at re (https://sdk.openui5.org/resources/~202310301319~/sap/ui/core/library-preload.js?eval:784:11678)
    at te (https://sdk.openui5.org/resources/~202310301319~/sap/ui/core/library-preload.js?eval:784:10566)
Caused by: Error: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://sdk.openui5.org/resources/~202310301319~/sap/ui/comp/filterbar/FilterBar.js'.
    at je (https://sdk.openui5.org/resources/~202310301319~/sap-ui-core.js:10:9567)
    at qe (https://sdk.openui5.org/resources/~202310301319~/sap-ui-core.js:10:13178)
    at Oe (https://sdk.openui5.org/resources/~202310301319~/sap-ui-core.js:10:15205)
    at Object.r [as require] (https://sdk.openui5.org/resources/~202310301319~/sap-ui-core.js:10:18588)
    at eval (https://sdk.openui5.org/resources/~202310301319~/sap/ui/core/library-preload.js?eval:784:8093)
    at new Promise (<anonymous>)
    at ne (https://sdk.openui5.org/resources/~202310301319~/sap/ui/core/library-preload.js?eval:784:8060)
    at re (https://sdk.openui5.org/resources/~202310301319~/sap/ui/core/library-preload.js?eval:784:11678)
    at te (https://sdk.openui5.org/resources/~202310301319~/sap/ui/core/library-preload.js?eval:784:10566)
    at Y (https://sdk.openui5.org/resources/~202310301319~/sap/ui/core/library-preload.js?eval:784:16268)

It looks like, when the system tries to access to [FilterBar JS code ](https://sdk.openui5.org/resources/~202310301319~/sap/ui/comp/filterbar/FilterBar.js) that resource it is not available.

I am calling the filterBar in the following way:

DATA(lo_fb) = page->header( )->dynamic_page_header( pinnable = abap_true ).
    lo_fb->filter_bar( id = `fbar` persistencykey = `myPersKey` usetoolbar = abap_false
          )->filter_group_items(
            )->filter_group_item( name = 'PEP' label = 'PEP' groupname = 'group1' visibleinfilterbar = abap_true
              )->fb_control(
                )->input( value = client->_bind_edit( mv_pspnr )
                          valuehelprequest = client->_event( 'FILTER_VALUE_HELP_PEP' ) showvaluehelp = abap_true
                       )->get_parent(  )->get_parent( )->get_parent(  ).

On the other hand, the sample 111 (Z2UI5_CL_DEMO_APP_111) it is also not working.

Could you review it, please?

Thanks in advance.

**Comment by oblomov-dev** [comment]
Demo 111 is fixed now.

Are you sure that this control is part of openUI5? When you change it to another SDK the file is found:
https://ui5.sap.com/1.116.0/resources/~202310301319~/sap/ui/comp/filterbar/FilterBar.js

When you have the possibility, you can adjust the bootstrapping of abap2UI5 and try again:
https://github.com/abap2UI5/abap2UI5-documentation/blob/main/docs/faq.md

**Comment by abagrevatil** [comment]
Solved. After changing to another SDK it works. Also, I confirm that now Demo 111 is fixed.

Thank you.
